### ISSUE TITLE
Associate repository to a channel

### ISSUE THREAD

**Issue by diananova** [MLH-Fellowship/github-discord-bot#15]
We need a command that associates a Github repository to a channel (maybe don't bother about private repos for now)

**Comment by diananova** [comment]
@gmelodie  @Laurell876 @kadinzhang 
- do we need a database for this? The channel-github repo association must be saved somewhere, right? 
- should we use MongoDB? https://towardsdatascience.com/creating-a-discord-bot-from-scratch-and-connecting-to-mongodb-828ad1c7c22e

**Comment by Laurell876** [comment]
Sure but we could store it in memory for now

**Comment by gmelodie** [comment]
A DB seems overkill. Maybe storing the information on a simple JSON file would do (it's not a heavily-structured and complex dataset right? Just a simple map ( `discord channel -> github repo` ).

**Comment by diananova** [comment]
Oh yeah that makes sense! We'll try using a JSON file.
